modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="command_add_mods"
version="2.0.0"
displayName="Command Add MODS"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Created By mcreator"
authors="Mega Super, BinbinvoGaming, MCreator"
description="by Mega Super And BinbinvoGaming"

[[dependencies.command_add_mods]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




